#!/bin/bash
#
id=$(xinput list | grep TouchPad | cut -d= -f 2 | cut -f 1)

case "$1" in
    (disable)
    xinput --set-prop "${id}" "Device Enabled" "0"
    notify-send -t 2000 'TouchPad OFF'
    ;;
    (enable)
    xinput --set-prop "${id}" "Device Enabled" "1"
    notify-send -t 2000 'TouchPad ON'
    ;;
esac
