[[theme]]
name = "slick"

[icons]
name = "awesome"
[icons.overrides]
bat = "  "
bat_discharging = "   "
bat_charging = "   "
bat_full = "   "

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/gchamoul/Mail/redhat-gmail/INBOX"]
threshold_warning = 1
threshold_critical = 10

[[block]]
block = "net"
device = "wlp58s0"
ssid = true
bitrate = true
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "enp0s31f6"
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "redhat0"
ip = true
speed_up = false
speed_down = false
interval = 5

# [[block]]
# block = "toggle"
# text = "4k"
# command_state = "xrandr | grep -Eq 'DP-[12345]-[12345] connected'"
# command_on = "~/.screenlayout/office.sh"
# command_off = "~/.screenlayout/laptop.sh"
# interval = 5

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 10
format = " {percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
timezone = "Europe/Paris"
format = "%a %d/%m/%d %H:%M:%S"
