#!/bin/sh

# Wait for program coming up
wait_for_program () {
  n=0
  while true
  do
    # PID of last background command
    if xdotool search --onlyvisible --pid $! 2>/dev/null; then
      break
    else
      if [ $n -eq 90 ]; then
        notify-send -u critical "Error during start"
        break
      else
        n=`expr $n + 1`
        sleep 0.5
      fi
    fi
  done
}

## Merge Xressources
xrdb -merge ~/.Xresources &

#xsetroot -solid '#000000' &
feh --bg-scale ~/Pictures/13236.png &

## Set startup volume (use pactl info to determine sink name)
pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo '60%' &

## Disable beeps
xset -b &

## Screen off after 5 minutes
exec --no-startup-id xset dpms 600 &

## Keybord layout setting
setxkbmap -layout us -variant altgr-intl -option grp:shift_shift_toggle &

## Set LCD brightness
xbacklight -set 100 &

## Clipboard manager
exec clipit &

## OSD
exec /usr/bin/dunst &

# linphone
exec /usr/bin/linphone --iconified &

# redshift-gtk
exec /usr/bin/redshift-gtk &

# shutter
exec /usr/bin/shutter --min_at_startup &

## Set touchpad off
synclient TouchpadOff=1

ws_chat="1: chat"
ws_mail="2: mail"
ws_twitter="3: twitter"
ws_1="1: "
ws_2="2: "
ws_3="3: "
ws_4="4: "
ws_5="5: "
ws_6="6: "
ws_7="7: "
ws_8="8: "
ws_9="9: "
ws_0="10: "

HDMI_YES=0
ANY_YES=0
xrandr | grep -q "HDMI1 connected" && HDMI_YES=1 && ANY_YES=1
xrandr | grep -q "VGA1 connected" && VGA_YES=1 && ANY_YES=1

if [ $HDMI_YES -eq 1]; then
  for w in chat mail twitter 1 2 3 4 5 6 7 8 9 0; do
    i3-msg "move workspace \$ws_${w}; to output HDMI1"
  done
fi

i3-msg workspace ${ws_1}

## Refresh and GO!
xrefresh &

#exec /usr/libexec/gnome-settings-daemon &
exec /usr/libexec/gnome-session/helpers/gnome-settings-daemon-helper &
exec /usr/libexec/polkit-gnome-authentication-agent-1 &
exec /usr/bin/gnome-screensaver &
exec /usr/bin/xautolock -time 1 \
    -locker "gnome-screensaver-command --lock --activate" \
    -notify 30 \
    -notifier "notify-send -u critical -t 10000 -- 'LOCKING screen in 30 seconds'" &
exec /usr/bin/gnome-keyring-daemon --start --components=gpg &
exec /usr/bin/gnome-keyring-daemon --start --components=ssh &
exec /usr/bin/gnome-keyring-daemon --start --components=secrets &
LC_ALL=C nm-applet &

exit 0
