#!/bin/sh

# Wait for program coming up
wait_for_program () {
    n=0
    while true; do
        # PID of last background command
        if xdotool search --onlyvisible --pid $! 2>/dev/null; then
            break
        else
            if [ $n -eq 200 ]; then
                notify-send -u critical "Error during start: last program $! did not started fast enough"
                break
            else
                n=`expr $n + 1`
                sleep 0.1
            fi
        fi
    done
}

## Determine connected monitors
DP_1_1=0
DP_1_2=0
xrandr | grep -Eq "DP-1-1 connected" && DP_1_1=1
xrandr | grep -Eq "DP-1-2 connected" && DP_1_2=1

if [ "$DP_1_1" -eq 1 ] && [ "$DP_1_2" -eq 1 ]; then
    . ${HOME}/.screenlayout/docked.sh
fi

#pointer_control enable
xrefresh &

# Update dmenu cache
dmenu_path >/dev/null &

exit 0
