#!/bin/sh

case "$1" in
   lock)
        xautolock -locknow
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        sudo pm-suspend
        ;;
    hibernate)
        sudo pm-hibernate
        ;;
    reboot)
        sudo reboot
        ;;
    shutdown)
        sudo poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
